### ISSUE TITLE
Error when try to generate a new App

### ISSUE THREAD

**Issue by magnumrocha** [zenorocha/generator-firefox-os#7]
I get an error when I tried to create a new project scaffold using this generator:

  var files   = this.expandFiles('**/*', { cwd: this.sourceRoot(), dot: true }
                                                     ^
TypeError: Object [object Object] has no method 'sourceRoot'
    at new module.exports (C:\Users\magnum.rocha\AppData\Roaming\npm\node_modules\generator-firefox-os\app\index.js:7:54
)
    at Environment.create (C:\Users\magnum.rocha\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\lib\e
nv\index.js:325:10)
    at Environment.run (C:\Users\magnum.rocha\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\lib\env\
index.js:361:24)
    at init (C:\Users\magnum.rocha\AppData\Roaming\npm\node_modules\yo\cli.js:95:7)
    at pre (C:\Users\magnum.rocha\AppData\Roaming\npm\node_modules\yo\cli.js:108:3)
    at Object.<anonymous> (C:\Users\magnum.rocha\AppData\Roaming\npm\node_modules\yo\cli.js:134:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

I am using a Windows 7 (64-bits) machine.

**Comment by xeBuz** [comment]
Yeoman change the filesystem methods: http://yeoman.io/authoring/file-system.html

Can you check this @zenorocha?

**Comment by jesobreira** [comment]
I'm able to reproduce this error under Ubuntu 64 bits.

**Comment by Wmitrut** [comment]
Same error here, Ubuntu 14.04, 64bits.

**Comment by mplacona** [comment]
Yeah same problem on Mac (Yosemite)

**Comment by zenorocha** [comment]
Fixed!
